[opener]
zathura = [
    { run = 'zathura %s1', orphan = true }
]

imv = [
    { run = 'imv %s', orphan = true }
]

nvim = [
    { run = 'nvim %s', block = true }
]

mpvv = [
    { run = 'mpvv %s', block = true }
]

[open]
rules = [
    { mime = "application/pdf", use = "zathura" },
    { mime = "image/*", use = "imv" },
    { mime = "video/*", use = "mpvv" },
    { url = "*", use = "nvim" },
]
